# Site title and subtitle. This is used in _includes/header.html
title: 'Poynt Developer'
#subtitle: 'Documentation and resources for PoyntOS App Developers'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/poynt/developer'

# Default categories (in order) to appear in the navigation
sections: [
    ['overview', '** Overview ** '],
    ['setup', '** Setup **'],
    ['onterminal', '** On-Terminal Apps **'],
    ['cloud', '** Cloud Apps **'],
    ['semi', '** Semi-Integration **'],
    ['peripherals', '** Integrating Peripherals** '],
    ['appstore', '** App Marketplace & App Review **'],
    ['acquirer', '** Acquirer/Gateway Integration **'],
    ['reference', '** References** '],

    ['doc', 'Documentation'],
    ['tut', 'Tutorials'],
    ['post', 'Posts'],
    ['ref', 'Reference']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/developer'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
