.TH "PoyntLib/models Directory Reference" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntLib/models Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPoyntDiscountObject\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntOrderItemObject\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntOrderItemTax\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntOrderObject\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntPaymentAmountObject\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntPaymentObject\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntSerializedObject\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntTerminal\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntTransaction\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntTransactionAmounts\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntTransactionObject\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntTransactionResponseObject\&.h\fP"
.br
.in -1c
