.TH "PoyntLib Directory Reference" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntLib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmodels\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBindex\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntDebug\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntLib\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntPOSConnectionManager\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntSDK\&.h\fP"
.br
.ti -1c
.RI "file \fBPoyntTerminalDiscover\&.h\fP"
.br
.in -1c
