.TH "PoyntLib/PoyntTerminalDiscover.h" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntLib/PoyntTerminalDiscover.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPoyntTerminalDiscover\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(^ \fBOnTerminalsFound\fP) (NSArray *terminal)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(^ OnTerminalsFound) (NSArray *terminal)"
\fBPoyntTerminalDiscover\fP  Base class for finding terminals on the same WIFI network 
.PP
Definition at line 16 of file PoyntTerminalDiscover\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Poynt-iOS-SDK from the source code\&.
