.TH "PoyntLib/PoyntLib.h" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntLib/PoyntLib.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PoyntPOSConnectionManager\&.h'\fP
.br
\fC#import 'PoyntPaymentAmountObject\&.h'\fP
.br
\fC#import 'PoyntDebug\&.h'\fP
.br
\fC#import 'PoyntDiscountObject\&.h'\fP
.br
\fC#import 'PoyntOrderItemTax\&.h'\fP
.br
\fC#import 'PoyntPaymentObject\&.h'\fP
.br
\fC#import 'PoyntOrderObject\&.h'\fP
.br
\fC#import 'PoyntOrderItemObject\&.h'\fP
.br
\fC#import 'PoyntTerminal\&.h'\fP
.br
\fC#import 'PoyntTerminalDiscover\&.h'\fP
.br
\fC#import 'PoyntTransactionObject\&.h'\fP
.br
\fC#import 'PoyntTransactionResponseObject\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Poynt-iOS-SDK from the source code\&.
