.TH "PoyntLib/models/PoyntOrderItemObject.h" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntLib/models/PoyntOrderItemObject.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br
\fC#import 'PoyntSerializedObject\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPoyntOrderItemObject\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBUnitOfMeasure\fP { \fBEACH\fP, \fBHOURS\fP, \fBDAYS\fP, \fBSECONDS\fP, \fBCRATE_OF_12\fP, \fBSIX_PACK\fP, \fBGALLON\fP, \fBLITRE\fP, \fBINCH\fP, \fBFOOT\fP, \fBMILLIMETER\fP, \fBCENTIMETER\fP, \fBMETER\fP, \fBSQUARE_METER\fP, \fBCUBIC_METER\fP, \fBGRAM\fP, \fBKG\fP, \fBPOUND\fP, \fBANNUAL\fP, \fBDEGREE_CELCIUS\fP, \fBDEGREE_FARENHEIT\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBUnitOfMeasure\fP"
\fBPoyntOrderItemObject\fP
.PP
The order item object depicts each item in an order and the details attached to it\&.
.PP
\fBNote:\fP
.RS 4
all numeric properties default to 0 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEACH \fP\fP
.TP
\fB\fIHOURS \fP\fP
.TP
\fB\fIDAYS \fP\fP
.TP
\fB\fISECONDS \fP\fP
.TP
\fB\fICRATE_OF_12 \fP\fP
.TP
\fB\fISIX_PACK \fP\fP
.TP
\fB\fIGALLON \fP\fP
.TP
\fB\fILITRE \fP\fP
.TP
\fB\fIINCH \fP\fP
.TP
\fB\fIFOOT \fP\fP
.TP
\fB\fIMILLIMETER \fP\fP
.TP
\fB\fICENTIMETER \fP\fP
.TP
\fB\fIMETER \fP\fP
.TP
\fB\fISQUARE_METER \fP\fP
.TP
\fB\fICUBIC_METER \fP\fP
.TP
\fB\fIGRAM \fP\fP
.TP
\fB\fIKG \fP\fP
.TP
\fB\fIPOUND \fP\fP
.TP
\fB\fIANNUAL \fP\fP
.TP
\fB\fIDEGREE_CELCIUS \fP\fP
.TP
\fB\fIDEGREE_FARENHEIT \fP\fP
.PP
Definition at line 21 of file PoyntOrderItemObject\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Poynt-iOS-SDK from the source code\&.
