.TH "PoyntLib/models/PoyntTransaction.h" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntLib/models/PoyntTransaction.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "protocol \fB<PoyntTransaction >\fP"
.br
.RI "When in doubt (or lazy) default to a \fBPoyntTransactionObject\fP\&. In cases where it is optimal to keep clear seperation, subscribe to \fBPoyntTransaction\fP \&. The transactionId property and dictionaryObject method are required\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Poynt-iOS-SDK from the source code\&.
