.TH "PoyntLib/models/PoyntTransactionAmounts.h" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntLib/models/PoyntTransactionAmounts.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br
\fC#import 'PoyntSerializedObject\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPoyntTransactionAmounts\fP"
.br
.RI "the transaction amounts in a \fBPoyntTransactionObject\fP amounts collection "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Poynt-iOS-SDK from the source code\&.
