.TH "PoyntLib/models/PoyntPaymentObject.h" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntLib/models/PoyntPaymentObject.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br
\fC#import 'PoyntSerializedObject\&.h'\fP
.br
\fC#import 'PoyntTransaction\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPoyntPaymentObject\fP"
.br
.RI "The \fBPoyntPaymentObject\fP is the required parameter for many sale and presales requests\&. The object can be built before making requests to the terminal\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Poynt-iOS-SDK from the source code\&.
