.TH "<PoyntSerializedObject >" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<PoyntSerializedObject > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PoyntSerializedObject\&.h>\fP
.PP
Inherits <NSObject>\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(NSDictionary *) \- \fBdictionaryObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPoyntSerializedObject\fP  all objects that are sent to the Poynt terminal subscribe to this protocol to verify proper json creation 
.PP
Definition at line 14 of file PoyntSerializedObject\&.h\&.
.SH "Method Documentation"
.PP 
.SS "\- (NSDictionary*) dictionaryObject "


.SH "Author"
.PP 
Generated automatically by Doxygen for Poynt-iOS-SDK from the source code\&.
