.TH "PoyntLib/models/PoyntSerializedObject.h" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntLib/models/PoyntSerializedObject.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "protocol \fB<PoyntSerializedObject >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Poynt-iOS-SDK from the source code\&.
