.TH "PoyntTransactionResponseObject" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoyntTransactionResponseObject \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PoyntTransactionResponseObject\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) \- \fBinitWithData:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSError * \fBresponseError\fP"
.br
.ti -1c
.RI "NSString * \fBstatus\fP"
.br
.ti -1c
.RI "NSArray * \fBtransactions\fP"
.br
.ti -1c
.RI "NSDictionary * \fBorder\fP"
.br
.ti -1c
.RI "NSDictionary * \fBrawJson\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file PoyntTransactionResponseObject\&.h\&.
.SH "Method Documentation"
.PP 
.SS "\- (id) initWithData: (NSData *) data"

.SH "Property Documentation"
.PP 
.SS "\- (NSDictionary*) order\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 15 of file PoyntTransactionResponseObject\&.h\&.
.SS "\- (NSDictionary*) rawJson\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 16 of file PoyntTransactionResponseObject\&.h\&.
.SS "\- (NSError*) responseError\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 12 of file PoyntTransactionResponseObject\&.h\&.
.SS "\- (NSString*) status\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [copy]\fP"

.PP
Definition at line 13 of file PoyntTransactionResponseObject\&.h\&.
.SS "\- (NSArray*) transactions\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 14 of file PoyntTransactionResponseObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Poynt-iOS-SDK from the source code\&.
