.TH "todo" 3 "Fri Nov 18 2016" "Version 0.1" "Poynt-iOS-SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBGlobal \fBPoyntTransactionObject::fundingSource\fP \fP" 1c
at current, we are not populating this field\&. Developers have access to the data in \fBPoyntTransactionResponseObject\&.rawJson\fP propety 
.PP

